baseURL = "http://localhost:1313/"
title = "肆月之风"
summaryLength = 1
## When enabled, creates URL of the form /filename.html instead of /filename/.
uglyURLs = false

languageCode = "zh"
defaultContentLanguage = "zh-cn"

theme = "hugo-acme"
themesdir = "../themes/"

## 定义链接规则
## https://gohugo.io/content-management/urls/#permalinks
[permalinks]
post = "/:filename"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
format = "format"

## markdown 开启对 html 的支持
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true

[blackfriday]
    extensions = ["hardLineBreak"]

## 定义输出格式
[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "JSON" ]
teams = [ "HTML" ]
section = [ "HTML", "JSON" ]

## 定义参数
[params]
    ## 控制博客一些静态资源的版本，便于更新
    version = "20201226"
    ## 博客副标题
    subtitle = "爱技术·爱分享"
    ## 博客的默认主题色
    themeColor = "#00c8ff"
    ## 列表和页面中封面图上的默认图标
    coverIcon = "folder"
    ## 文章页默认封面图【废弃】
    # coverImage = "https://schepp.dev/img/natalya-letunova-gF8aHM445P4-unsplash.jpg"
    ## 文章页封面图遮罩层颜色，可设置透明度等，建议优先使用封面图的主色
    # coverColor = "#00c8ff"
    ## 文章页封面图分割：0-默认小图模式 1-大图模式
    coverStyle = 0
    ## 文章页封面图上标题的颜色风格：0-默认 1-明亮 2-暗色
    titleStyle = 0
    ## 列表页默认封面图
    listCoverImage = "https://static.acme.top/wp-content/uploads/2019/01/headerbg_archive.jpg"

## 二维码赞助渠道设置，注释掉后将隐藏
[params.sponsor]
    title = "赞赏"
    description = "如果文章对您有帮助，欢迎给作者打赏"

    [[params.sponsor.channels]]
    name = "支付宝"
    qrcode = "https://static.acme.top/wp-content/uploads/2018/12/alipay_qrcode.png"

    [[params.sponsor.channels]]
    name = "微信"
    qrcode = "https://static.acme.top/wp-content/uploads/2018/12/weixinpay_qrcode.png"

## 社交平台，url为空则会忽略
[[params.socialPlatforms]]
id = "github"
name = "GitHub"
url = "https://github.com/niqingyang"

[[params.socialPlatforms]]
id = "rss"
name = "RSS"
url = ""

[[params.socialPlatforms]]
id = "mail"
name = "邮箱"
url = "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=niqy@qq.com"

[[params.socialPlatforms]]
id = "weibo"
name = "微博"
url = ""

[[params.socialPlatforms]]
id = "wechat"
name = "微信"
url = ""

[[params.socialPlatforms]]
id = "douban"
name = "豆瓣"
url = ""

[[params.socialPlatforms]]
id = "twitter"
name = "Twitter"
url = ""

[[params.socialPlatforms]]
id = "facebook"
name = "Facebook"
url = ""

[[params.socialPlatforms]]
id = "gplus"
name = "Google+"
url = ""

[[params.socialPlatforms]]
id = "linkedin"
name = "LinkedIn"
url = ""

[[params.socialPlatforms]]
id = "dribbble"
name = "Dribbble"
url = ""

[[params.socialPlatforms]]
id = "flickr"
name = "Flickr"
url = ""

[[params.footerLinks]]
name = "冀ICP备18027707号"
url = "https://beian.miit.gov.cn/"

[menu]

    ## 顶部菜单

    [[menu.main]]
    name = "首页"
    identifier = "home"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "开发笔记"
    identifier = "develop"
    url = "/categories/develop"
    weight = 2

    [[menu.main]]
    name = "前端开发"
    identifier = "web"
    url = "/categories/web"
    weight = 3

    [[menu.main]]
    name = "运维笔记"
    identifier = "ops"
    url = "/categories/ops"
    weight = 4

    [[menu.main]]
    name = "更多"
    identifier = "more"
    url = "#"
    weight = 5

    [[menu.main]]
    name = "实用软件"
    parent = "more"
    identifier = "software"
    url = "/categories/software"
    weight = 6

    [[menu.main]]
    name = "好文收藏"
    parent = "more"
    identifier = "sharing"
    url = "/categories/sharing"
    weight = 7

    [[menu.main]]
    name = "博客状态"
    parent = "more"
    identifier = "record"
    url = "/categories/record"
    weight = 8

    [[menu.main]]
    name = "给我留言"
    parent = "more"
    identifier = "guestbook"
    url = "/guestbook"
    weight = 9

    [[menu.main]]
    name = "关于"
    parent = "more"
    identifier = "about"
    url = "/about"
    weight = 10

    ## 底部菜单

    [[menu.footer]]
    name = "关于"
    identifier = "about"
    url = "/about"
    weight = 1

    [[menu.footer]]
    name = "赞助"
    identifier = "footer-zanzhu"
    url = "/zanzhu"
    weight = 2

    [[menu.footer]]
    name = "链接"
    identifier = "footer-links"
    url = "/links"
    weight = 3

    [[menu.footer]]
    name = "留言簿"
    identifier = "footer-guestbook"
    url = "/guestbook"
    weight = 4

    [[menu.footer]]
    name = "阿里云优惠券"
    identifier = "footer-aliyun"
    url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=ggzv2k92"
    weight = 5



